services:
  cigniter-docker:
    container_name: conteiner-projeto
    build: .
    volumes:
      - ./app:/var/www/html
    ports:
      - 8080:80
  
  mysql_db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=base
      - MYSQL_USER=vitim
      - MYSQL_PASSWORD=senha
      - MYSQL_ROOT_PASSWORD=root
    ports:
    - 3306:3306
  
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1